### ISSUE TITLE
Error When Running App in Emulator

### ISSUE THREAD

**Issue by dekarpaulvictor** [bryanbill/letters#1]
Hi, I'm getting this error when running the app in an Android emulator. I'm using an emulator created in Android Studio using the latest stock Android 13 system image.

[Here](https://ibb.co/VjVT5my) is a link to a screenshot of the error.

The backend service runs fine.

Assuming I'm one of your app users, how would you go about advising me to solve the problem?

**Comment by bryanbill** [comment]
@dekarpaulvictor I'm experiencing a time-out error while trying to view the screenshot. Could you please upload it to this thread?

**Comment by bryanbill** [comment]
Thanks for bringing this up. The problem occurs when someone tries to make a post with fewer than 200 characters in our app. To avoid this issue, users should aim to create posts with 200 characters or more. However, our app currently only guards against posts with fewer than 100 characters.

To resolve this, I'm working on a new update that will fix the problem while keeping the 100-character guard intact.
